# Generated by Django 5.2 on 2025-05-08 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='discount', to='apps.product'),
        ),
    ]
